# Generated by Django 6.0.4 on 2026-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="subject",
            field=models.CharField(default="Général", max_length=100),
        ),
    ]
