# Generated by Django 6.0.4 on 2026-06-10 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_missing_quiz_subject"),
        ("planning", "0002_revisionplan_exam_date_revisionplan_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="availability_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="revision_session_end_after_start",
            ),
        ),
    ]
