# Generated by Django 6.0.4 on 2026-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_availability_availability_end_after_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionsession",
            name="color",
            field=models.CharField(default="#8B6CF6", max_length=20),
        ),
        migrations.AddField(
            model_name="revisionsession",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="revisionsession",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="revisionsession",
            name="title",
            field=models.CharField(default="Séance de révision", max_length=255),
        ),
    ]
