# Generated by Django 6.0.4 on 2026-06-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
    migrations.AddField(
        model_name="quiz",
        name="subject",
        field=models.CharField(max_length=100, default="Quiz"),
    ),
]
