# Generated by Django 6.0.4 on 2026-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursepdf_subject_folder_coursepdf_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepdf',
            name='subject',
            field=models.CharField(default='Général', max_length=100),
        ),
    ]
